package org.ademun.timetablebot.handler.callback;

public enum Action {
  MANAGER_ADD_DISCIPLINE,
  MANAGER_REMOVE_DISCIPLINE,
  ADD_NEW_DISCIPLINE,
  ADD_EXISTING_DISCIPLINE,
  REMOVE_DISCIPLINE,
  MANAGER_ADD_PROFESSOR,
  MANAGER_REMOVE_PROFESSOR,
  ADD_NEW_PROFESSOR,
  ADD_EXISTING_PROFESSOR,
  REMOVE_PROFESSOR
}
